#!/bin/bash
#
# 内存测试脚本
#
# 用法：$0 <datadir> <timelimit> <memlimit> <chrootdir> <workdir> <run-uuid> <run>
#
# <datadir>      包含数据文件的文件夹的绝对路径
# <timelimit>    运行时间限制，格式为 %d:%d，如 1:3 表示测试点时间限制
#                为 1s，如果运行时间超过 3s 则结束程序
# <memlimit>     运行内存限制，单位为 KB
# <chrootdir>    子环境
# <workdir>      程序的工作文件夹，为了保证安全，请务必将运行路径设置
#                为空文件夹，特别是保证不可以包含标准输出文件
# <run-uuid>     运行的 uuid，用于索引运行文件夹位置
# <run>          运行程序的脚本的绝对路径
#
# 必须包含的环境变量：
# "RUNGUARD"     runguard 的路径
#
# 默认的比较脚本都可以放在配置服务中

set -e
trap 'cleanup ; error' EXIT

cleanup ()
{
    # 删除创建过的文件

    if [ -s runguard.err ]; then
        echo "************* runguard error *************" >> system.out
        cat runguard.err >> system.out
    fi
}

cleanexit ()
{
    set +e
    trap - EXIT

    cleanup

    exit $1
}

# 导入 runcheck 函数
. "$JUDGE_UTILS/utils.sh"
. "$JUDGE_UTILS/logging.sh"

CPUSET=""
CPUSET_OPT=""
OPTINT=1
while getopts "n:" opt; do
    case $opt in
        n)
            OPTSET="$OPTARG"
            ;;
        :)
            >&2 echo "Option -$OPTARG requires an argument."
            ;;
    esac
done

shift $((OPTIND-1))
[ "$1" == "--" ] && shift

if [ -n "$CPUSET" ]; then
    CPUSET_OPT="-P $CPUSET"
fi

LOGFILE="$LOGDIR/judge.$(hostname | cut -d . -f 1).log"
LOGLEVEL=$LOG_DEBUG
PROGNAME="$(basename "$0")"

if [ "$DEBUG" ]; then
    export VERBOSE=$LOG_DEBUG
else
    export VERBOSE=$LOG_ERR
fi

GAINROOT="sudo -n"
PROGRAM="compile/run"

[ $# -ge 4] || error "not enough arguments"

DATADIR="$1"; shift
TIMELIMIT="$1"; shift
MEMLIMIT="$1"; shift
CHROOTDIR="$1"; shift
WORKDIR="$1"; shift
RUN_UUID="$1"; shift
RUN_SCRIPT="$1"

TESTIN="$DATADIR/input"
TESTOUT="$DATADIR/output"

[ -d "$TESTIN" ] || error "input data does not exist: $TESTIN"
[ -d "$TESTOUT" ] || error "output data does not exist: $TESTOUT"
if [ ! -d "$WORKDIR" ] || [ ! -w "$WORKDIR" ] || [ ! -x "$WORKDIR" ]; then
    error "Working directory does not exist: $WORKDIR"
fi

[ -x "$WORKDIR/$PROGRAM" ] || error "Program does not exist"
[ -x "$COMPARE_SCRIPT" ] || error "Compare script does not exist"
[ -x "$RUN_SCRIPT" ] || error "Run script does not exist"
[ -x "$RUNGUARD" ] || error "runguard does not exist"

chmod a+x "$WORKDIR"

# 检查运行脚本

RUNDIR="$WORKDIR/run-$RUN_UUID"
mkdir -p "$RUNDIR"
chmod a+rwx "$RUNDIR"

cd "$RUNDIR"

touch judge.out
touch program.out program.err
touch program.meta runguard.err
touch compare.meta compare.err

mkdir -p "$RUNDIR/run" # 运行的临时文件都在这里
mkdir -p "$RUNDIR/feedback"
mkdir -p "$RUNDIR/work"
mkdir -p "$RUNDIR/work/judge"
mkdir -p "$RUNDIR/work/judge_utils"
mkdir -p "$RUNDIR/work/run"
mkdir -p "$RUNDIR/merged"
# 将测试数据文件夹（内含输入数据，且其中 testdata.in 为标准输入数据文件名），编译好的程序，运行文件夹通过 overlayfs 绑定
mount -t aufs none -odirs="$RUNDIR/run"=rw:"$WORKDIR/compile"=ro:"$TESTIN"=ro "$RUNDIR/work/judge"
mount --bind -o ro "$JUDGE_UTILS" "$RUNDIR/work/judge_utils"
mount --bind -o ro "$RUN_SCRIPT" "$RUNDIR/work/run"
mount -t aufs none -odirs="$RUNDIR/work"=rw:"$CHROOTDIR"=ro "$RUNDIR/merged"

# 我们不检查选手程序的返回值，比如 C 程序的 main 函数没有写 return 会导致返回值非零，这种不是崩溃导致的
runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT \
    --root "$RUNDIR/merged" \
    --work /judge \
    --nproc $PROCLIMIT \
    --no-core-dumps \
    --streamsize $FILELIMIT \
    --user "$RUNUSER" \
    --group "$RUNGROUP" \
    --wall-time $TIMELIMIT \
    --memory-limit $MEMLIMIT \
    --file-limit $FILELIMIT \
    --standard-output-file valgrind.xml \
    --standard-error-file program.err \
    --out-meta program.meta -- \
    valgrind --leak-check=full --undef-value-errors=yes --track-origins=yes --xml=yes --xml-fd=1 -- \
    /run/run testdata.in program.out /judge/run 2>runguard.err

umount -f "$RUNDIR/work/judge" >/dev/null 2>&1  || /bin/true
umount -f "$RUNDIR/work/judge_utils" >/dev/null 2>&1  || /bin/true
umount -f "$RUNDIR/work/run" >/dev/null 2>&1  || /bin/true
umount -f "$RUNDIR/merged" >/dev/null 2>&1  || /bin/true
rm -rf "$RUNDIR/run"
rm -rf "$RUNDIR/merged"
rm -rf "$RUNDIR/work"
# RUNDIR 还剩下 program.meta, program.err, system.out, runguard.err 供评测客户端检查
# RUNDIR 由评测客户端删除

# Make sure that all feedback files are owned by the current
# user/group, so that we can append content.
$GAINROOT chown -R "$(id -un):" "$RUNDIR/feedback"
chmod -R go-w feedback

if [ ! -r program.meta ]; then
    error "'program.meta' is not readable"
fi

logmsg $LOG_DEBUG "Checking program run status"

timeused=$(grep '^time-used: '    program.meta | sed 's/time-used: //'   )
cputime= $(grep '^cpu-time: '     program.meta | sed 's/cpu-time: //'    )
walltime=$(grep '^wall-time: '    program.meta | sed 's/wall-time: //'   )
progexit=$(grep '^exitcode: '     program.meta | sed 's/exitcode: //'    )
stdout=  $(grep '^stdout-bytes: ' program.meta | sed 's/stdout-bytes: //')
stderr=  $(grep '^stderr-bytes: ' program.meta | sed 's/stderr-bytes: //')
memused= $(grep '^memory-bytes: ' program.meta | sed 's/memory-bytes: //')
signal=  $(grep '^signal: '       program.meta | sed 's/signal: //'      )
resource_usage="\
runtime: ${cputime}s cpu, ${walltime}s wall
memory used: ${memused} bytes"

if grep '^time-result: .*timelimit' program.meta >/dev/null 2>&1; then
    echo "Time Limit Exceeded" >> system.out
    echo "$resource_usage" >> system.out
    cleanexit ${E_TIME_LIMIT:-1}
fi

if grep -E '^output-truncated: ([a-z]+,)*stdout(,[a-z]+)*' program.meta >/dev/null 2>&1; then
    echo "Output Limit Exceeded" >> system.out
    echo "$resource_usage" >> system.out
    cleanexit ${E_OUTPUT_LIMIT:-1}
fi

runcheck python3 "$PROGNAME/convert.py" valgrind.xml $RUNDIR/feedback/report.txt 2>feedback/judgemessage.txt
case $exitcode in
    0)
        echo "Accepted" >> system.out
        echo "$resource_usage" >> system.out
        cleanexit ${E_ACCEPTED:-1}
        ;;
    1)
        echo "Wrong Answer" >> system.out
        echo "$resource_usage" >> system.out
        cleanexit ${E_WRONG_ANSWER:-1}
        ;;
    *)
        logmsg $LOG_ERR "Comparing failed with exitcode $exitcode, compare script output:\\n$(cat feedback/judgemessage.txt)"
        cleanexit ${E_COMPARE_ERROR:-1}
        ;;
esac
