stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  DEPLOY_NAME: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}

cache:
  paths:
    - ext # GitHub 连接速度太慢了。。

build-docker:
  stage: build
  only:
    - master
    - development
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - chmod +x .install_dependence.sh
    - ./.install_dependence.sh
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
  tags: ["shell"]

deploy-prod:
  stage: deploy
  only: 
    - master
  image: dtzar/helm-kubectl
  script:
    - sed -i "s~<ENVIRONMENT>~production~g" k8s-deploy.yaml
    - ./deploy.sh
  tags: ["docker"]


deploy-dev:
  stage: deploy
  only: 
    - development
  image: dtzar/helm-kubectl
  script:
    - sed -i "s~<ENVIRONMENT>~test~g" k8s-deploy.yaml
    - ./deploy.sh
  tags: ["docker"]
