variables:
  VERSION: "4.0"

stages:
  - prepare
  - host-build
  - host-test
  - docker-build
  - docker-deploy
  - docker-clean

project-prepare-302:
  script:
    - chmod +x .install_dependence.sh
    - ./.install_dependence.sh
  stage: prepare
  only:
    - ProgrammingWorker
    - ChoiceWorker
    - framework
    - develop
    - master
  tags:
    - test

project-prepare:
  script:
    - chmod +x .install_dependence.sh
    - ./.install_dependence.sh
  stage: prepare
  only:
    - master
  tags:
    - judge-builder

project-docker-build-302:
  script:
    - docker build -f=docker/Dockerfile.run -t=matrix-docker-registry:5000/matrix-judge:${VERSION} .
  stage: docker-build
  only:
    - master
  tags:
    - test

project-docker-build:
  script:
    - docker build -f=docker/Dockerfile.run -t=matrix-docker-registry:5000/matrix-judge:${VERSION} .
  stage: docker-build
  only:
    - master
  tags:
    - judge-builder

project-docker-deploy-302:
  script:
    - docker push matrix-docker-registry:5000/matrix-judge:${VERSION}
  stage: docker-deploy
  only:
    - master
  tags:
    - test

project-docker-deploy:
  script:
    - docker push matrix-docker-registry:5000/matrix-judge:${VERSION}
  stage: docker-deploy
  only:
    - master
  tags:
    - judge-builder

project-docker-test-clean-302:
  script:
    - docker rmi $(docker images -aqf "dangling=true") || true
  stage: docker-clean
  only:
    - develop
  tags:
    - test
