#!/bin/sh
#
# Oclint 静态分析
#
# 用法：$0 <testin> <progout> <commands...>

TESTIN="$1"; shift
PROGOUT="$1"

if [ -f "$TESTIN" ]; then
    exec oclint "$@" < "$TESTIN" > "$PROGOUT"
else
    exec oclint "$@" > "$PROGOUT"
fi
